### PR TITLE
Updated the Page

### PR DESCRIPTION
**Pull request by sudeepshukla930**
Little bit Contribution to the main page

### CODE REVIEW

**Review by avinashkranjan — APPROVED** [review]
LGTM...💯..Thanks for Contributing

**Comment by sudeepshukla930** [comment]
@avinashkranjan  , Hey can you please add label of  **"Hacktoberfest accepted"** while merging my pull request..
It will would really helpful for me..
@avinashkranjan  , I request you to please add tag of  **"Hacktoberfest accepted"**..

**Comment by avinashkranjan** [comment]
@sudeepshukla930 PR accepted is counted as in hacktoberfest.. Don't worry .. I have added hacktoberfest in tag..

**Comment by sudeepshukla930** [comment]
@avinashkranjan  Sir, I have just checked my profile in Hacktoberfest website .. still PR has not counted.
I request you to please add the **"hacktoberfest accepted "** label to my PR.. then only it will count..Please Sir

**Comment by avinashkranjan** [comment]
@sudeepshukla930  **_Read It Carefully_**

chrome_DgpMeYwQDM

**Comment by sudeepshukla930** [comment]
@avinashkranjan  Thankyou Sir. It has been counted :)

**Pull request merged**
